language: node_js
node_js:
- "14.15.0"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        - npm run test:coveralls
        #- jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage