language: node_js
node_js:
- "14.15.0"


jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        - jest --coverage && coveralls ./coverage/lcov.info 
        - npm run coveralls 